SELECTED_STOCKS = "selected-stocks"
SELECTED_STRATS = "selected-strategies"
SELECTED_DATE = "selected-date"
STOCK_SELECT_DROPDOWN = "stock-select-dropdown"
STRAT_RADIO_ITEM = "strategy-radio-item"
SINGLE_STRAT_DROPDOWN = "single-strategy-dropdown"
MULTI_STRAT_DROPDOWN = "multiple-strategy-dropdown"
STRAT_CARD = "strategy-card"
MULTI_STRAT_CARD = "multiple-strategy-card"
SINGLE_STRAT_CARD = "single-strategy-card"
DATE_SELECT = "date-select"

SIMULATE_BUTTON = "simulate-button"
ERROR_SIMULATE_BUTTON = "error-simulate-button"
